name: "Build development"

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run: sudo apt-get update && sudo apt-get -y install cc65
      - uses: actions/checkout@v2
      - name: mkdir build
        run: mkdir -p build
      - name: clean
        run: make clean
      - name: prepare ntsc
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SECRET }}" --output original.nes game_ntsc.gpg
      - name: build ntsc
        run: make patch.ips
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: pellsson
          path: |
            patch.ips
            README.md
