name: "Build development"

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run: sudo apt-get update && sudo apt-get -y install cc65
      - uses: actions/checkout@v2
      - name: prepare pal
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SECRET }}" --output original_pal.nes game_pal.gpg
      - name: build pal
        run: PAL=1 make patch.ips && mv patch.ips patch_pal.ips
      - name: prepare ntsc
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SECRET }}" --output original.nes game_ntsc.gpg
      - name: build ntsc
        run: make patch.ips
      - name: clean
        run: make clean
      - name: zip
        run: zip pellsson.zip README.md patch.ips patch_pal.ips
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: pellsson.zip
          path: pellsson.zip
