name: "Build release"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run: sudo apt-get update && sudo apt-get -y install cc65
      - uses: actions/checkout@v2
      - name: mkdir build
        run: mkdir -p build
      - name: clean
        run: make clean
      - name: prepare pal
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SECRET }}" --output original_pal.nes game_pal.gpg
      - name: build pal
        run: PAL=1 make patch.ips && mv patch.ips patch_pal.ips
      - name: prepare ntsc
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SECRET }}" --output original.nes game_ntsc.gpg
      - name: build ntsc
        run: make patch.ips
      - name: clean
        run: make clean
      - name: zip
        run: zip "pellsson_${GITHUB_REF#refs/*/}.zip" README.md patch.ips patch_pal.ips
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: files
          path: "*.zip"

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bodyFile: CHANGELOG
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: true
      - name: get assets
        uses: actions/download-artifact@v2
        with:
          name: files
          path: files
      - name: upload assets
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./files/*"]'
